export const cultTaskTemplate = {
  name: "Limpeza e Organização dos Cultos",
  title: "Limpeza e Organização Antes do Culto",
  summary: "Preparação completa dos ambientes e equipes antes do culto.",
  description:
    "Modelo baseado no documento “Cheque Liste de Limpeza e Organização Antes dos Cultos 2025”. Defina a data e o responsável ao criar a tarefa.",
  color: "#7c3aed",
  icon: "check-circle",
  items: [
    "[Templo Maior] Realizar a limpeza interna do templo",
    "[Templo Maior] Conferir lâmpadas e iluminação",
    "[Templo Maior] Conferir os aparelhos de ar-condicionado",
    "[Templo Maior] Conferir a sonoplastia",
    "[Templo Maior] Conferir os microfones",
    "[Templo Maior] Conferir se todas as caixas de som estão funcionando",
    "[Templo Maior] Definir responsável pela mídia, letras dos hinos e data show",
    "[Templo Maior] Organizar as cadeiras",
    "[Templo Maior] Colocar envelopes de dízimos, primícias e ofertas atrás das cadeiras",
    "[Templo Maior — Decoração] Conferir se as cortinas estão organizadas",
    "[Templo Maior — Decoração] Ligar os lustres",
    "[Templo Maior — Decoração] Ligar a cruz e a menorá",
    "[Área externa] Conferir a iluminação externa",
    "[Área externa] Conferir a iluminação do jardim",
    "[Área externa] Conferir os LEDs da fachada da igreja",
    "[Área externa] Realizar a limpeza do pátio",
    "[Estacionamento] Definir os responsáveis pelo estacionamento",
    "[Recepção] Recepcionar com alegria e desejar um ótimo culto a todos",
    "[Recepção] Definir responsáveis pela introdução e recepção",
    "[Recepção] Coletar testemunhos para apresentação no culto",
    "[Recepção] Coletar nome e telefone dos visitantes",
    "[Camarim] Realizar a limpeza",
    "[Camarim] Limpar os banheiros e conferir papel higiênico, sabão e toalha para as mãos",
    "[Camarim] Organizar o ambiente",
    "[Camarim] Preparar o lanche da tarde",
    "[Camarim] Conferir os aparelhos de ar-condicionado",
    "[Auditório / Salinha Kids] Realizar a limpeza",
    "[Auditório / Salinha Kids] Organizar mesas e cadeiras",
    "[Auditório / Salinha Kids] Conferir as lâmpadas",
    "[Auditório / Salinha Kids] Conferir o ar-condicionado",
    "[Auditório / Salinha Kids] Conferir se a TV está funcionando",
    "[Banheiros] Realizar a limpeza",
    "[Banheiros] Repor papéis higiênicos",
    "[Banheiros] Repor papéis-toalha",
    "[Banheiros] Repor sabão líquido para lavar as mãos",
    "[Banheiros] Conferir as lâmpadas",
    "[Banheiros] Esvaziar as lixeiras dos sanitários e dos papéis-toalha",
    "[Banheiros] Colocar naftalina para melhorar o cheiro do ambiente",
    "[Bebedouro] Realizar a limpeza",
    "[Bebedouro] Repor copos descartáveis",
    "[Bebedouro] Esvaziar a lixeira dos copos descartáveis",
    "[Escritório] Realizar a limpeza",
    "[Escritório] Conferir os aparelhos de ar-condicionado",
    "[Escritório] Conferir as lâmpadas",
    "[Escritório] Preparar café e lanche na sala do ministro",
    "[Primícias, Dízimos e Ofertas] Definir o ministro",
    "[Primícias, Dízimos e Ofertas] Definir os responsáveis por ungir",
    "[Primícias, Dízimos e Ofertas] Verificar envelopes e gazofilácios",
    "[Ministro da noite] Deixar uma taça com água natural para o ministro",
    "[Ministro da noite] Disponibilizar lenços para secar o suor",
    "[Ministro da noite] Disponibilizar óleo de unção",
    "[Encerramento] Definir responsável pela despedida dos participantes",
    "[Encerramento] Coletar informações dos visitantes",
  ],
} as const;

export const cultTaskTemplateEmails = [
  "apostoloreuber@gmail.com",
  "amos.desenvolvedor@gmail.com",
  "ediceu30@gmail.com",
] as const;
